# Generated by Django 5.0.3 on 2024-04-02 13:04

import apps.fr.models
import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('changed_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Changed_at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID identification')),
                ('original_image', models.ImageField(upload_to=apps.fr.models.get_user_fr_image_path, verbose_name='Original image')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fr_original_images', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Original image',
                'verbose_name_plural': 'Original images',
            },
        ),
        migrations.CreateModel(
            name='RecognizedFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('changed_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Changed_at')),
                ('face_image', models.TextField(verbose_name='Face image in base64')),
                ('vector', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None, verbose_name='Vector')),
                ('original_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recognized_faces', to='fr.originalimage', verbose_name='Original image')),
            ],
            options={
                'verbose_name': 'Recognized face',
                'verbose_name_plural': 'Recognized faces',
            },
        ),
    ]
