# Generated by Django 5.0.2 on 2024-03-30 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="structureunit",
            old_name="department_leader",
            new_name="department_members",
        ),
    ]
