# Generated by Django 5.0.2 on 2024-03-30 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_rename_department_leader_structureunit_department_members"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeeposition",
            name="work_shift",
        ),
        migrations.AlterField(
            model_name="workshift",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="workshift",
            name="schedule",
            field=models.CharField(max_length=255, verbose_name="Schedule"),
        ),
        migrations.CreateModel(
            name="EmployeeWorkShift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.employeeposition",
                        verbose_name="Employee",
                    ),
                ),
                (
                    "work_shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.workshift",
                        verbose_name="Work_Shift",
                    ),
                ),
            ],
        ),
    ]
