# Generated by Django 5.0.2 on 2024-03-30 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_remove_employeeposition_work_shift_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChangeTimeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(verbose_name="Event date")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("day_off", "Отгул"),
                            ("vacation", "Отпуск"),
                            ("sick_leave", "Больничный"),
                            ("business_trip", "Командировка"),
                            ("coming", "Прибытие"),
                            ("leaving", "Убытие"),
                            ("coming_hr", "Прибытие [HR]"),
                            ("leaving_hr", "Убытие [HR]"),
                            ("other", "Другое"),
                        ],
                        max_length=100,
                        verbose_name="Event type",
                    ),
                ),
                ("comment", models.TextField(verbose_name="Comment")),
                (
                    "change_status",
                    models.CharField(
                        choices=[
                            ("in_process", "В процессе"),
                            ("confirmed", "Принято"),
                            ("canceled", "Отменено"),
                        ],
                        max_length=100,
                        verbose_name="Event type",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application",
                        to="main.employee",
                        verbose_name="Employee",
                    ),
                ),
            ],
        ),
    ]
