# Generated by Django 5.0.3 on 2024-03-31 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structureunit',
            name='department_members',
        ),
    ]
