# Generated by Django 5.0.3 on 2024-03-31 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_remove_structureunit_department_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='structureunit',
            name='department_members',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.employee', verbose_name='Department Members'),
        ),
    ]
