# Generated by Django 5.0.3 on 2024-03-31 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_remove_structureunit_department_members_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='structureunit',
            old_name='department_members',
            new_name='employee',
        ),
    ]
