# Generated by Django 5.0.3 on 2024-03-31 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_rename_department_members_structureunit_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structureunit',
            name='employee',
        ),
    ]
