# Generated by Django 5.0.3 on 2024-03-31 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_remove_structureunit_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeposition',
            name='work_shift',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='work_shift',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='employee_type',
            new_name='employment_type',
        ),
        migrations.AddField(
            model_name='employeeposition',
            name='structure_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.structureunit', verbose_name='Structure unit'),
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='WorkShift',
        ),
    ]
