# Generated by Django 5.0.3 on 2024-03-31 18:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_remove_employeeposition_work_shift_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('changed_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Changed_at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID identification')),
                ('name', models.CharField(max_length=255, verbose_name='Shift Name')),
                ('schedule', models.CharField(max_length=100, verbose_name='Shift Schedule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='employment_type',
            new_name='employee_type',
        ),
        migrations.AddField(
            model_name='employee',
            name='structure_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees_structure_unit', to='organizations.structureunit', verbose_name='Structure unit'),
        ),
        migrations.AlterField(
            model_name='employeeposition',
            name='structure_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='organizations.structureunit', verbose_name='Structure unit'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('changed_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Changed_at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID identification')),
                ('date', models.DateTimeField(verbose_name='Event date')),
                ('type', models.CharField(choices=[('day_off', 'Отгул'), ('vacation', 'Отпуск'), ('sick_leave', 'Больничный'), ('business_trip', 'Командировка'), ('coming', 'Прибытие'), ('leaving', 'Убытие'), ('coming_hr', 'Прибытие [HR]'), ('leaving_hr', 'Убытие [HR]'), ('other', 'Другое')], max_length=100, verbose_name='Event type')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('application_status', models.CharField(choices=[('for_consideration', ' На рассмотрений'), ('approved', 'Одобрено'), ('canceled', 'Отменено')], default=' На рассмотрений', max_length=100, verbose_name='Status')),
                ('employee', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='application', to='organizations.employee', verbose_name='Employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='work_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_shift', to='organizations.workshift', verbose_name='Work shift'),
        ),
    ]
