# Generated by Django 5.0.3 on 2024-03-31 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_workshift_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeposition',
            name='structure_unit',
        ),
        migrations.AddField(
            model_name='employeeposition',
            name='structure_unit',
            field=models.ManyToManyField(blank=True, null=True, related_name='employees', to='organizations.structureunit', verbose_name='Structure unit'),
        ),
    ]
