# Generated by Django 5.0.3 on 2024-03-31 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_remove_employeeposition_structure_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeposition',
            name='structure_unit',
        ),
        migrations.AddField(
            model_name='employeeposition',
            name='structure_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='organizations.structureunit', verbose_name='Structure unit'),
        ),
    ]
