# Generated by Django 5.0.3 on 2024-03-31 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_remove_employeeposition_structure_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='structure_unit',
        ),
        migrations.RemoveField(
            model_name='employeeposition',
            name='structure_unit',
        ),
    ]
