# Generated by Django 5.0.3 on 2024-04-01 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0016_remove_structureunit_department_members_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee_type',
            new_name='employment_type',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='structure_unit',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='work_shift',
        ),
        migrations.RemoveField(
            model_name='employeeposition',
            name='work_shift',
        ),
        migrations.AlterField(
            model_name='employeeposition',
            name='structure_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='organizations.structureunit', verbose_name='Structure unit'),
        ),
    ]
