# Generated by Django 5.0.3 on 2024-04-01 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0018_employee_work_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='structure_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.structureunit', verbose_name='Structure unit'),
        ),
    ]
