# Generated by Django 5.0.3 on 2024-04-03 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fr', '0002_alter_recognizedface_vector'),
        ('organizations', '0019_employee_structure_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('changed_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Changed_at')),
                ('employee_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.employeeevent', verbose_name='Employee event')),
                ('recognized_face', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fr.recognizedface', verbose_name='Recognized')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
