# Generated by Django 5.0.3 on 2024-04-03 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0020_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeWorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('changed_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Changed_at')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.employee', verbose_name='Employee')),
                ('work_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.workshift', verbose_name='Work shift')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
