# Generated by Django 5.0.3 on 2024-04-03 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0021_employeeworkshift'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeWorkShift',
        ),
    ]
