# Generated by Django 5.0.3 on 2024-04-04 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0022_delete_employeeworkshift'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.employee', verbose_name='Employee'),
        ),
    ]
