# Generated by Django 5.0.3 on 2024-04-05 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0024_positionname_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionname',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='organizations.departmentname', verbose_name='Parent'),
        ),
    ]
