# Generated by Django 5.0.3 on 2024-04-05 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0025_alter_positionname_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positionname',
            name='parent',
        ),
    ]
