# Generated by Django 5.0.3 on 2024-04-05 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0026_remove_positionname_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeposition',
            name='work_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.workshift', verbose_name='Work Shift'),
        ),
    ]
