# Generated by Django 5.0.3 on 2024-04-05 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0027_employeeposition_work_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='work_shift',
        ),
    ]
